on: pull_request
name: CTF Homework
jobs:
  gitHubActionForPytest:
    name: Logic Checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test function logic
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: python setup.py develop && pytest
